services:
  - type: web
    name: letterboxd-recommender
    env: docker
    dockerfilePath: ./Dockerfile
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: REDIS_URL
        fromService:
          name: letterboxd-redis
          type: redis
          property: connectionString
      - key: DATABASE_URL
        value: sqlite:///./data/letterboxd_rec.db

  - type: redis
    name: letterboxd-redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []
